import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGenerated1777192875185 implements MigrationInterface {
    name = 'AutoGenerated1777192875185'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."ingestion_jobs_source_type_enum" AS ENUM('pdf', 'image', 'receipt')`);
        await queryRunner.query(`CREATE TYPE "public"."ingestion_jobs_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed')`);
        await queryRunner.query(`CREATE TABLE "ingestion_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "original_filename" character varying NOT NULL, "storage_path" character varying NOT NULL, "mime_type" character varying NOT NULL, "source_type" "public"."ingestion_jobs_source_type_enum" NOT NULL DEFAULT 'pdf', "status" "public"."ingestion_jobs_status_enum" NOT NULL DEFAULT 'pending', "error_message" text, "metadata" jsonb, "extracted_text" text, "chunk_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "completed_at" TIMESTAMP, CONSTRAINT "PK_78a3cba789582043cfc8ba82edd" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "ingestion_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."ingestion_jobs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ingestion_jobs_source_type_enum"`);
    }

}
